### ISSUE TITLE
Pre-Project Checklist

### ISSUE THREAD

**Issue by JMB-TAMTRIAL** [JMB-TAMTRIAL/TIA-Website#2]
Update P2:

- [x]  confirm signed Project Brief with complete scope, specs and timeline included. Posted in P2
- [x] login credentials for existing Partner website (Drupal);
- [x] post login credentials for existing host and domain registrar in P2;
- [x] confirm WordPress and WooCommerce plugin keys are posted to P2;
- [x]  create Team Google Drive folder, add link to P2;
- [x] create ZOHO CRM for project, post link to P2;
- [x] add Partner branding guide and design guidelines to Google Drive folder;
